SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `openwords_words`
--

-- --------------------------------------------------------

--
-- Table structure for table `languages`
--

CREATE TABLE `languages` (
`id` int(11) NOT NULL,
  `language` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `code` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `meta_info` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `display_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `languages`
--

INSERT INTO `languages` (`id`, `language`, `code`, `meta_info`, `display_name`) VALUES
(1, "[english]", "en", "", ""),
(2, "[abau]", "aau", "", ""),
(3, "[abkhaz]", "ab", "", ""),
(4, "[abenaki]", "abe", "", ""),
(5, "[abaza]", "abq", "", ""),
(6, "[acehnese]", "ace", "", ""),
(7, "[adyghe]", "ady", "", ""),
(8, "[avestan]", "ae", "", ""),
(9, "[afrikaans]", "af", "", ""),
(10, "[angor]", "agg", "", ""),
(11, "[aghul]", "agx", "", ""),
(12, "[ainu]", "ain", "", ""),
(13, "[akan]", "ak", "", ""),
(14, "[akkadian]", "akk", "", ""),
(15, "[akhvakh]", "akv", "", ""),
(16, "[alabama]", "akz", "", ""),
(17, "[aleut]", "ale", "", ""),
(18, "[alune]", "alp", "", ""),
(19, "[southern altai]", "alt", "", ""),
(20, "[amharic]", "am", "", ""),
(21, "[ama (new guinea)]", "amm", "", ""),
(22, "[amuzgo]", "amu", "", ""),
(23, "[aragonese]", "an", "", ""),
(24, "[old english]", "ang", "", ""),
(25, "[andi]", "ani", "", ""),
(26, "[uab meto]", "aoz", "", ""),
(27, "[apache#western apache]", "apw", "", ""),
(28, "[arabic]", "ar", "", ""),
(29, "[aramaic#syriac][aramaic#hebrew]", "arc", "", ""),
(30, "[mapudungun]", "arn", "", ""),
(31, "[arapaho]", "arp", "", ""),
(32, "[arabic#egyptian arabic]", "arz", "", ""),
(33, "[assamese]", "as", "", ""),
(34, "[assiniboine]", "asb", "", ""),
(35, "[american sign language]", "ase", "", ""),
(36, "[asturian]", "ast", "", ""),
(37, "[atikamekw]", "atj", "", ""),
(38, "[avar]", "av", "", ""),
(39, "[alviri-vidari]", "avd", "", ""),
(40, "[aymara]", "ay", "", ""),
(41, "[azeri]", "az", "", ""),
(42, "[bashkir]", "ba", "", ""),
(43, "[baluchi]", "bal", "", ""),
(44, "[balinese]", "ban", "", ""),
(45, "[bavarian]", "bar", "", ""),
(46, "[batak toba]", "bbc", "", ""),
(47, "[budukh]", "bdk", "", ""),
(48, "[west coast bajau]", "bdr", "", ""),
(49, "[belarusian]", "be", "", ""),
(50, "[beja]", "bej", "", ""),
(51, "[bemba]", "bem", "", ""),
(52, "[bulgarian]", "bg", "", ""),
(53, "[banggai]", "bgz", "", ""),
(54, "[banjarese]", "bjn", "", ""),
(55, "[blackfoot]", "bla", "", ""),
(56, "[bambara]", "bm", "", ""),
(57, "[bengali]", "bn", "", ""),
(58, "[bontoc]", "bnc", "", ""),
(59, "[banda (indonesia)]", "bnd", "", ""),
(60, "[bunun]", "bnn", "", ""),
(61, "[bintulu]", "bny", "", ""),
(62, "[tibetan]", "bo", "", ""),
(63, "[borôro]", "bor", "", ""),
(64, "[botlikh]", "bph", "", ""),
(65, "[bilba]", "bpz", "", ""),
(66, "[breton]", "br", "", ""),
(67, "[brunei bisaya]", "bsb", "", ""),
(68, "[buryat]", "bua", "", ""),
(69, "[buginese]", "bug", "", ""),
(70, "[catalan]", "ca", "", ""),
(71, "[ch'orti']", "caa", "", ""),
(72, "[caddo]", "cad", "", ""),
(73, "[chamicuro]", "ccc", "", ""),
(74, "[chakma]", "ccp", "", ""),
(75, "[chechen]", "ce", "", ""),
(76, "[cebuano]", "ceb", "", ""),
(77, "[gaulish]", "cel-gau", "", ""),
(78, "[chamorro]", "ch", "", ""),
(79, "[catawba]", "chc", "", ""),
(80, "[cahuilla]", "chl", "", ""),
(81, "[eastern mari]", "chm", "", ""),
(82, "[choctaw]", "cho", "", ""),
(83, "[cherokee]", "chr", "", ""),
(84, "[cheyenne]", "chy", "", ""),
(85, "[cia-cia]", "cia", "", ""),
(86, "[chru]", "cje", "", ""),
(87, "[chamalal]", "cji", "", ""),
(88, "[shor]", "cjs", "", ""),
(89, "[kurdish#sorani]", "ckb", "", ""),
(90, "[chukchi]", "ckt", "", ""),
(91, "[klallam]", "clm", "", ""),
(92, "[chinese#mandarin][chinese#wu]", "cmn", "", "普通话"),
(93, "[corsican]", "co", "", ""),
(94, "[comanche]", "com", "", ""),
(95, "[coptic]", "cop", "", ""),
(96, "[cree]", "cr", "", ""),
(97, "[crimean tatar]", "crh", "", ""),
(98, "[cora]", "crn", "", ""),
(99, "[carrier]", "crx", "", ""),
(100, "[czech]", "cs", "", ""),
(101, "[kashubian]", "csb", "", ""),
(102, "[old church slavonic]", "cu", "", ""),
(103, "[kuna]", "cuk", "", ""),
(104, "[chuvash]", "cv", "", ""),
(105, "[welsh]", "cy", "", ""),
(106, "[danish]", "da", "", ""),
(107, "[dargwa]", "dar", "", ""),
(108, "[dyirbal]", "dbl", "", ""),
(109, "[tsez]", "ddo", "", ""),
(110, "[german]", "de", "", ""),
(111, "[casiguran dumagat agta]", "dgc", "", ""),
(112, "[dogrib]", "dgr", "", ""),
(113, "[dalmatian]", "dlm", "", ""),
(114, "[chinese#dungan]", "dng", "", ""),
(115, "[sorbian#lower sorbian]", "dsb", "", ""),
(116, "[dutch#middle dutch]", "dum", "", ""),
(117, "[dhivehi]", "dv", "", ""),
(118, "[ewe]", "ee", "", ""),
(119, "[egyptian]", "egy", "", ""),
(120, "[greek]", "el", "", ""),
(121, "[middle english]", "enm", "", ""),
(122, "[esperanto]", "eo", "", ""),
(123, "[eritai]", "ert", "", ""),
(124, "[spanish]", "es", "", ""),
(125, "[eshtehardi]", "esh", "", ""),
(126, "[yup'ik]", "esu", "", ""),
(127, "[estonian]", "et", "", ""),
(128, "[basque]", "eu", "", ""),
(129, "[even]", "eve", "", ""),
(130, "[evenki]", "evn", "", ""),
(131, "[persian]", "fa", "", ""),
(132, "[fula]", "ff", "", ""),
(133, "[finnish]", "fi", "", ""),
(134, "[fijian]", "fj", "", ""),
(135, "[montana salish]", "fla", "", ""),
(136, "[faroese]", "fo", "", ""),
(137, "[fon]", "fon", "", ""),
(138, "[siraya]", "fos", "", ""),
(139, "[french]", "fr", "", ""),
(140, "[french#middle french]", "frm", "", ""),
(141, "[french#old french]", "fro", "", ""),
(142, "[franco-provençal]", "frp", "", ""),
(143, "[frisian#north frisian]", "frr", "", ""),
(144, "[friulian]", "fur", "", ""),
(145, "[frisian#west frisian][west frisian]", "fy", "", ""),
(146, "[irish]", "ga", "", ""),
(147, "[gagauz]", "gag", "", ""),
(148, "[gayo]", "gay", "", ""),
(149, "[scottish gaelic]", "gd", "", ""),
(150, "[godoberi]", "gdo", "", ""),
(151, "[mehri]", "gdq", "", ""),
(152, "[ge'ez]", "gez", "", ""),
(153, "[hinukh]", "gin", "", ""),
(154, "[galician]", "gl", "", ""),
(155, "[nanai]", "gld", "", ""),
(156, "[german#middle high german]", "gmh", "", ""),
(157, "[low german#middle low german]", "gml", "", ""),
(158, "[guaraní]", "gn", "", ""),
(159, "[german#old high german]", "goh", "", ""),
(160, "[gothic]", "got", "", ""),
(161, "[greek#ancient greek][greek#ancient]", "grc", "", ""),
(162, "[gujarati]", "gu", "", ""),
(163, "[manx]", "gv", "", ""),
(164, "[hausa]", "ha", "", ""),
(165, "[haida]", "hai", "", ""),
(166, "[chinese#hakka]", "hak", "", ""),
(167, "[hawaiian]", "haw", "", ""),
(168, "[hebrew]", "he", "", ""),
(169, "[hindi]", "hi", "", ""),
(170, "[hiligaynon]", "hil", "", ""),
(171, "[hittite]", "hit", "", ""),
(172, "[hopi]", "hop", "", ""),
(173, "[sorbian#upper sorbian]", "hsb", "", ""),
(174, "[haitian creole]", "ht", "", ""),
(175, "[hungarian]", "hu", "", ""),
(176, "[hunzib]", "huz", "", ""),
(177, "[armenian]", "hy", "", ""),
(178, "[interlingua]", "ia", "", ""),
(179, "[iban]", "iba", "", ""),
(180, "[indonesian]", "id", "", ""),
(181, "[interlingue]", "ie", "", ""),
(182, "[igbo]", "ig", "", ""),
(183, "[sichuan yi]", "ii", "", ""),
(184, "[iranun]", "ill", "", ""),
(185, "[ilocano]", "ilo", "", ""),
(186, "[ingush]", "inh", "", ""),
(187, "[ido]", "io", "", ""),
(188, "[mingo]", "iro-min", "", ""),
(189, "[icelandic]", "is", "", ""),
(190, "[istriot]", "ist", "", ""),
(191, "[italian]", "it", "", ""),
(192, "[itelmen]", "itl", "", ""),
(193, "[inuktitut]", "iu", "", ""),
(194, "[ingrian]", "izh", "", ""),
(195, "[japanese]", "ja", "", ""),
(196, "[yan-nhangu]", "jay", "", ""),
(197, "[lojban]", "jbo", "", ""),
(198, "[yamdena]", "jmd", "", ""),
(199, "[jarai]", "jra", "", ""),
(200, "[javanese]", "jv", "", ""),
(201, "[georgian]", "ka", "", ""),
(202, "[karakalpak]", "kaa", "", ""),
(203, "[kabyle]", "kab", "", ""),
(204, "[bezhta]", "kap", "", ""),
(205, "[javanese#old javanese]", "kaw", "", ""),
(206, "[kabardian]", "kbd", "", ""),
(207, "[khanty]", "kca", "", ""),
(208, "[kemak]", "kem", "", ""),
(209, "[ket]", "ket", "", ""),
(210, "[kongo]", "kg", "", ""),
(211, "[kikuyu]", "ki", "", ""),
(212, "[kickapoo]", "kic", "", ""),
(213, "[khakas]", "kjh", "", ""),
(214, "[khinalug]", "kjj", "", ""),
(215, "[kazakh]", "kk", "", ""),
(216, "[guugu yimidhirr]", "kky", "", ""),
(217, "[greenlandic]", "kl", "", ""),
(218, "[klamath-modoc]", "kla", "", ""),
(219, "[gamilaraay]", "kld", "", ""),
(220, "[khmer]", "km", "", ""),
(221, "[kurdish#kurmanji]", "kmr", "", ""),
(222, "[kannada]", "kn", "", ""),
(223, "[kankanaey]", "kne", "", ""),
(224, "[korean]", "ko", "", ""),
(225, "[komi-permyak]", "koi", "", ""),
(226, "[konkani]", "kok", "", ""),
(227, "[karata]", "kpt", "", ""),
(228, "[komi-zyrian]", "kpv", "", ""),
(229, "[koryak]", "kpy", "", ""),
(230, "[kimaragang]", "kqr", "", ""),
(231, "[karachay-balkar]", "krc", "", ""),
(232, "[karelian]", "krl", "", ""),
(233, "[kedang]", "ksx", "", ""),
(234, "[kurdish#kurmanji][kurdish#sorani]", "ku", "", ""),
(235, "[kumyk]", "kum", "", ""),
(236, "[bagvalal]", "kva", "", ""),
(237, "[cornish]", "kw", "", ""),
(238, "[kyrgyz]", "ky", "", ""),
(239, "[coastal kadazan]", "kzj", "", ""),
(240, "[latin]", "la", "", ""),
(241, "[ladino]", "lad", "", ""),
(242, "[luxembourgish]", "lb", "", ""),
(243, "[lak]", "lbe", "", ""),
(244, "[lezgi]", "lez", "", ""),
(245, "[limburgish]", "li", "", ""),
(246, "[ligurian]", "lij", "", ""),
(247, "[livonian]", "liv", "", ""),
(248, "[lampung api]", "ljp", "", ""),
(249, "[lakota]", "lkt", "", ""),
(250, "[ladin]", "lld", "", ""),
(251, "[lombard]", "lmo", "", ""),
(252, "[lingala]", "ln", "", ""),
(253, "[lao]", "lo", "", ""),
(254, "[lithuanian]", "lt", "", ""),
(255, "[latgalian]", "ltg", "", ""),
(256, "[leti]", "lti", "", ""),
(257, "[luhya]", "luy", "", ""),
(258, "[latvian]", "lv", "", ""),
(259, "[madurese]", "mad", "", ""),
(260, "[makasar]", "mak", "", ""),
(261, "[maasai]", "mas", "", ""),
(262, "[western bukidnon manobo]", "mbb", "", ""),
(263, "[moksha]", "mdf", "", ""),
(264, "[mandar]", "mdr", "", ""),
(265, "[central melanau]", "mel", "", ""),
(266, "[mende]", "men", "", ""),
(267, "[meru]", "mer", "", ""),
(268, "[mauritian creole]", "mfe", "", ""),
(269, "[mayo]", "mfy", "", ""),
(270, "[malagasy]", "mg", "", ""),
(271, "[maori]", "mi", "", ""),
(272, "[miami]", "mia", "", ""),
(273, "[mi'kmaq]", "mic", "", ""),
(274, "[minangkabau]", "min", "", ""),
(275, "[southern puebla mixtec]", "mit", "", ""),
(276, "[macedonian]", "mk", "", ""),
(277, "[malayalam]", "ml", "", ""),
(278, "[western maninkakan]", "mlq", "", ""),
(279, "[mongolian]", "mn", "", ""),
(280, "[manchu]", "mnc", "", ""),
(281, "[mansi]", "mns", "", ""),
(282, "[montagnais]", "moe", "", ""),
(283, "[mohawk]", "moh", "", ""),
(284, "[marathi]", "mr", "", ""),
(285, "[maricopa]", "mrc", "", ""),
(286, "[maranao]", "mrw", "", ""),
(287, "[malay#jawi][malay][malay#rumi]", "ms", "", ""),
(288, "[maltese]", "mt", "", ""),
(289, "[creek]", "mus", "", ""),
(290, "[miyako]", "mvi", "", ""),
(291, "[tagal murut]", "mvv", "", ""),
(292, "[burmese]", "my", "", ""),
(293, "[pirahã]", "myp", "", ""),
(294, "[erzya]", "myv", "", ""),
(295, "[nauruan]", "na", "", ""),
(296, "[nahuatl]", "nah", "", ""),
(297, "[chinese#min nan]", "nan", "", ""),
(298, "[neapolitan]", "nap", "", ""),
(299, "[nama]", "naq", "", ""),
(300, "[classical nahuatl]", "nci", "", ""),
(301, "[low german]", "nds", "", ""),
(302, "[low german#german low german]", "nds-de", "", ""),
(303, "[nepali]", "ne", "", ""),
(304, "[newari]", "new", "", ""),
(305, "[nias]", "nia", "", ""),
(306, "[nganasan]", "nio", "", ""),
(307, "[nivkh]", "niv", "", ""),
(308, "[dutch]", "nl", "", ""),
(309, "[norwegian#nynorsk]", "nn", "", ""),
(310, "[norwegian][norwegian#bokmål]", "no", "", ""),
(311, "[nogai]", "nog", "", ""),
(312, "[old norse]", "non", "", ""),
(313, "[novial]", "nov", "", ""),
(314, "[nuer]", "nus", "", ""),
(315, "[navajo]", "nv", "", ""),
(316, "[occitan]", "oc", "", ""),
(317, "[frisian#old frisian]", "ofs", "", ""),
(318, "[ojibwe]", "oj", "", ""),
(319, "[o'odham]", "ood", "", ""),
(320, "[oriya]", "or", "", ""),
(321, "[ossetian][ossetian#iron][ossetian#digor]", "os", "", ""),
(322, "[osage]", "osa", "", ""),
(323, "[old saxon]", "osx", "", ""),
(324, "[ottoman turkish]", "ota", "", ""),
(325, "[punjabi]", "pa", "", ""),
(326, "[pangasinan]", "pag", "", ""),
(327, "[middle persian][persian#middle persian]", "pal", "", ""),
(328, "[kapampangan]", "pam", "", ""),
(329, "[papiamentu]", "pap", "", ""),
(330, "[plautdietsch]", "pdt", "", ""),
(331, "[phoenician]", "phn", "", ""),
(332, "[pali]", "pi", "", ""),
(333, "[powhatan]", "pim", "", ""),
(334, "[pitjantjatjara]", "pjt", "", ""),
(335, "[polish]", "pl", "", ""),
(336, "[paulohi]", "plh", "", ""),
(337, "[pamona]", "pmf", "", ""),
(338, "[malecite-passamaquoddy]", "pqm", "", ""),
(339, "[old prussian]", "prg", "", ""),
(340, "[pashto]", "ps", "", ""),
(341, "[portuguese]", "pt", "", ""),
(342, "[quechua]", "qu", "", ""),
(343, "[quileute]", "qui", "", ""),
(344, "[rade]", "rad", "", ""),
(345, "[rapa nui]", "rap", "", ""),
(346, "[romagnol]", "rgn", "", ""),
(347, "[rohingya]", "rhg", "", ""),
(348, "[romansch]", "rm", "", ""),
(349, "[kirundi]", "rn", "", ""),
(350, "[romanian]", "ro", "", ""),
(351, "[jèrriais]", "roa-jer", "", ""),
(352, "[norman]", "roa-nor", "", ""),
(353, "[portuguese#old portuguese]", "roa-opt", "", ""),
(354, "[tae']", "rob", "", ""),
(355, "[romani]", "rom", "", ""),
(356, "[russian]", "ru", "", ""),
(357, "[rusyn]", "rue", "", ""),
(358, "[aromanian]", "rup", "", ""),
(359, "[megleno-romanian]", "ruq", "", ""),
(360, "[rutul]", "rut", "", ""),
(361, "[kinyarwanda]", "rw", "", ""),
(362, "[yaeyama]", "rys", "", ""),
(363, "[okinawan]", "ryu", "", ""),
(364, "[sanskrit]", "sa", "", ""),
(365, "[yakut]", "sah", "", ""),
(366, "[sasak]", "sas", "", ""),
(367, "[santali]", "sat", "", ""),
(368, "[sardinian]", "sc", "", ""),
(369, "[sicilian]", "scn", "", ""),
(370, "[scots]", "sco", "", ""),
(371, "[sindhi]", "sd", "", ""),
(372, "[sassarese sardinian]", "sdc", "", ""),
(373, "[sardinian#gallurese sardinian]", "sdn", "", ""),
(374, "[northern sami]", "se", "", ""),
(375, "[seri]", "sei", "", ""),
(376, "[irish#old irish]", "sga", "", ""),
(377, "[serbo-croatian#cyrillic][serbo-croatian][serbo-croatian#roman]", "sh", "", ""),
(378, "[shoshone]", "shh", "", ""),
(379, "[tashelhit]", "shi", "", ""),
(380, "[shan]", "shn", "", ""),
(381, "[sinhalese]", "si", "", ""),
(382, "[sebop]", "sib", "", ""),
(383, "[kildin sami]", "sjd", "", ""),
(384, "[ter sami]", "sjt", "", ""),
(385, "[slovak]", "sk", "", ""),
(386, "[slovene]", "sl", "", ""),
(387, "[samoan]", "sm", "", ""),
(388, "[inari sami]", "smn", "", ""),
(389, "[simeulue]", "smr", "", ""),
(390, "[skolt sami]", "sms", "", ""),
(391, "[sumbawa]", "smw", "", ""),
(392, "[shona]", "sn", "", ""),
(393, "[bau bidayuh]", "sne", "", ""),
(394, "[somali]", "so", "", ""),
(395, "[albanian]", "sq", "", ""),
(396, "[sardinian#campidanese sardinian]", "sro", "", ""),
(397, "[swazi]", "ss", "", ""),
(398, "[sotho]", "st", "", ""),
(399, "[frisian#saterland frisian]", "stq", "", ""),
(400, "[saanich]", "str", "", ""),
(401, "[sundanese]", "su", "", ""),
(402, "[sumerian]", "sux", "", ""),
(403, "[swedish]", "sv", "", ""),
(404, "[swahili]", "sw", "", ""),
(405, "[sangir]", "sxn", "", ""),
(406, "[aramaic#classical syriac]", "syc", "", ""),
(407, "[silesian]", "szl", "", ""),
(408, "[tamil]", "ta", "", ""),
(409, "[tabasaran]", "tab", "", ""),
(410, "[tulu]", "tcy", "", ""),
(411, "[telugu]", "te", "", ""),
(412, "[dena'ina]", "tfn", "", ""),
(413, "[tajik]", "tg", "", ""),
(414, "[thai]", "th", "", ""),
(415, "[tigrinya]", "ti", "", ""),
(416, "[tigre]", "tig", "", ""),
(417, "[tindi]", "tin", "", ""),
(418, "[turkmen]", "tk", "", ""),
(419, "[tsakhur]", "tkr", "", ""),
(420, "[tagalog]", "tl", "", ""),
(421, "[tlingit]", "tli", "", ""),
(422, "[talysh][talysh#cyrillic][talysh#latin]", "tly", "", ""),
(423, "[tswana]", "tn", "", ""),
(424, "[tontemboan]", "tnt", "", ""),
(425, "[tongan]", "to", "", ""),
(426, "[tok pisin]", "tpi", "", ""),
(427, "[tupinambá]", "tpn", "", ""),
(428, "[tonkawa]", "tqw", "", ""),
(429, "[turkish]", "tr", "", ""),
(430, "[tatar]", "tt", "", ""),
(431, "[tat]", "ttt", "", ""),
(432, "[twi]", "tw", "", ""),
(433, "[taos]", "twf", "", ""),
(434, "[tocharian b]", "txb", "", ""),
(435, "[tahitian]", "ty", "", ""),
(436, "[tuvan]", "tyv", "", ""),
(437, "[tz'utujil]", "tzj", "", ""),
(438, "[central atlas tamazight]", "tzm", "", ""),
(439, "[udi]", "udi", "", ""),
(440, "[udmurt]", "udm", "", ""),
(441, "[uyghur]", "ug", "", ""),
(442, "[ugaritic]", "uga", "", ""),
(443, "[ukrainian]", "uk", "", ""),
(444, "[umbundu]", "umb", "", ""),
(445, "[lenape#munsee]", "umu", "", ""),
(446, "[lenape#unami]", "unm", "", ""),
(447, "[urdu]", "ur", "", ""),
(448, "[uzbek][uzbek#cyrillic]", "uz", "", ""),
(449, "[venda]", "ve", "", ""),
(450, "[venetian]", "vec", "", ""),
(451, "[veps]", "vep", "", ""),
(452, "[vietnamese]", "vi", "", ""),
(453, "[mbabaram]", "vmb", "", ""),
(454, "[volapük]", "vo", "", ""),
(455, "[votic]", "vot", "", ""),
(456, "[võro]", "vro", "", ""),
(457, "[walloon]", "wa", "", ""),
(458, "[waray-waray]", "war", "", ""),
(459, "[warlpiri]", "wbp", "", ""),
(460, "[welsh#middle welsh]", "wlm", "", ""),
(461, "[wallisian]", "wls", "", ""),
(462, "[wolof]", "wo", "", ""),
(463, "[chinese#wu]", "wuu", "", ""),
(464, "[wangaaybuwan-ngiyambaa]", "wyb", "", ""),
(465, "[vilamovian]", "wym", "", ""),
(466, "[kalmyk]", "xal", "", ""),
(467, "[breton#middle breton]", "xbm", "", ""),
(468, "[armenian#old armenian]", "xcl", "", ""),
(469, "[darkinjung]", "xda", "", ""),
(470, "[xhosa]", "xh", "", ""),
(471, "[hadrami]", "xhd", "", ""),
(472, "[bakung]", "xkl", "", ""),
(473, "[median]", "xme", "", ""),
(474, "[phrygian]", "xpg", "", ""),
(475, "[sabaean]", "xsa", "", ""),
(476, "[sherpa]", "xsr", "", ""),
(477, "[tocharian a]", "xto", "", ""),
(478, "[yiddish]", "yi", "", ""),
(479, "[yidiny]", "yii", "", ""),
(480, "[yakan]", "yka", "", ""),
(481, "[northern yukaghir]", "ykg", "", ""),
(482, "[yoruba]", "yo", "", ""),
(483, "[yonaguni]", "yoi", "", ""),
(484, "[nenets]", "yrk", "", ""),
(485, "[yucatec maya]", "yua", "", ""),
(486, "[yuchi]", "yuc", "", ""),
(487, "[chinese#cantonese]", "yue", "", ""),
(488, "[havasupai-walapai-yavapai]", "yuf", "", ""),
(489, "[isthmus zapotec]", "zai", "", ""),
(490, "[central berawan]", "zbc", "", ""),
(491, "[ngazidja comorian]", "zdj", "", ""),
(492, "[záparo]", "zro", "", ""),
(493, "[zulu]", "zu", "", ""),
(494, "[zazaki]", "zza", "", "");

-- --------------------------------------------------------

--
-- Table structure for table `words`
--

CREATE TABLE `words` (
`word_id` bigint(20) NOT NULL,
  `language_id` int(11) NOT NULL,
  `word` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `meta_info` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `updated_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `contributor_id` char(4) COLLATE utf8_unicode_ci NOT NULL,
  `translation_md5` binary(16) NOT NULL COMMENT 'the sig for global translation or clarification'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `word_connections`
--

CREATE TABLE `word_connections` (
`connection_id` bigint(20) NOT NULL,
  `word1_id` bigint(20) NOT NULL,
  `word1_language` int(11) NOT NULL,
  `word2_id` bigint(20) NOT NULL,
  `word2_language` int(11) NOT NULL,
  `connection_type` smallint(6) NOT NULL,
  `updated_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `contributor_id` char(4) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `languages`
--
ALTER TABLE `languages`
 ADD PRIMARY KEY (`id`), ADD UNIQUE KEY `code` (`code`);

--
-- Indexes for table `words`
--
ALTER TABLE `words`
 ADD PRIMARY KEY (`word_id`), ADD UNIQUE KEY `unique_translation` (`language_id`,`word`,`translation_md5`), ADD KEY `word` (`word`), ADD KEY `language_id` (`language_id`), ADD KEY `translation_md5` (`translation_md5`);

--
-- Indexes for table `word_connections`
--
ALTER TABLE `word_connections`
 ADD PRIMARY KEY (`connection_id`), ADD UNIQUE KEY `unique_connection` (`word1_id`,`word2_id`,`connection_type`,`contributor_id`), ADD KEY `word1_id` (`word1_id`), ADD KEY `word1_language` (`word1_language`), ADD KEY `word2_id` (`word2_id`), ADD KEY `word2_language` (`word2_language`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `languages`
--
ALTER TABLE `languages`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
--
-- AUTO_INCREMENT for table `words`
--
ALTER TABLE `words`
MODIFY `word_id` bigint(20) NOT NULL AUTO_INCREMENT;
--
-- AUTO_INCREMENT for table `word_connections`
--
ALTER TABLE `word_connections`
MODIFY `connection_id` bigint(20) NOT NULL AUTO_INCREMENT;
--
-- Constraints for dumped tables
--

--
-- Constraints for table `word_connections`
--
ALTER TABLE `word_connections`
ADD CONSTRAINT `word2_lang_fk` FOREIGN KEY (`word2_language`) REFERENCES `languages` (`id`),
ADD CONSTRAINT `word1_fk` FOREIGN KEY (`word1_id`) REFERENCES `words` (`word_id`),
ADD CONSTRAINT `word1_lang_fk` FOREIGN KEY (`word1_language`) REFERENCES `languages` (`id`),
ADD CONSTRAINT `word2_fk` FOREIGN KEY (`word2_id`) REFERENCES `words` (`word_id`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
